name: CI-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v6-beta 
    - name: mvn clean install
      run: |
        mvn clean install
        mvn test
      
      
    
