name: CI-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v6-beta 
    - name: mvn clean install
      run: |
        mvn clean install
        mvn test

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: build-artifacts
        path: |
          target/*.jar
          target/*.war
    
      
      
    
